services:
  app:
    build: ./app
    restart: always
    ports:
      - 5000:5000
#      - 5001:5000
    volumes:
      - ./app:/app
    depends_on:
      - database
    environment:
      - FLASK_DEBUG=1

  database:
    image: postgres:latest
    env_file:
      - app/.env
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data: